# 2. Error Handling with Try-Except Block
# Assignment:
# Write a program that takes two numbers as input and divides the first number by the second.
# Use a try-except block to handle potential division by zero errors.


try:
    num1 = int(input("Enter first number: "))
    num2 = int(input("Enter second number: "))
    result = num1/num2
    print("Result: ",result)
except:
    print("Error Occured")